### ISSUE TITLE
ApiKey Invalid

### ISSUE THREAD

**Issue by terbaik97** [drehimself/laravel-movies-example#1]
Can you show such an dummy example to write on .env file 
TMDB_TOKEN=
I have follow all of your yt and also pull ur master but still give me an Invalid Api Key 
I already run in Postman and its work.
Thank you again.

**Comment by nraloux** [comment]
Try with API read access token (v4 auth)

> Can you show such an dummy example to write on .env file
> TMDB_TOKEN=
> I have follow all of your yt and also pull ur master but still give me an Invalid Api Key
> I already run in Postman and its work.
> Thank you again.

**Comment by drehimself** [comment]
I don't know what to tell you, everything I've done is in the YouTube video.

**Comment by sioannides** [comment]
> Try with API read access token (v4 auth)
> 
> > Can you show such an dummy example to write on .env file
> > TMDB_TOKEN=
> > I have follow all of your yt and also pull ur master but still give me an Invalid Api Key
> > I already run in Postman and its work.
> > Thank you again.

The TMDB_TOKEN environment variable is not defined in .env.example file...so when you do a composer install and the .env is generated, the variable is not there...
Of course you could open the file and add it manually :)
