### ISSUE TITLE
impossible to install on my pc

### ISSUE THREAD

**Issue by Chrisdeparis** [drehimself/laravel-movies-example#2]
Hello Andre !

I just tried to install your repo on my pc but i had an error

failed to open stream : No such file or directory in
C:\laragon\www\laravel-movies-example\public\index.php on line 24

**Comment by drehimself** [comment]
I've just added installation instructions. It looks like you forgot to `composer install`

**Comment by Chrisdeparis** [comment]
ok dre thanks
