### ISSUE TITLE
Issue on movie show page

### ISSUE THREAD

**Issue by usmanjdn93** [drehimself/laravel-movies-example#3]
hi..there is error occurring on movie show page when you click on any movie which don't have `poster_path` 

try with this => `movies/607989`

**Comment by drehimself** [comment]
I think I fixed this in the latest commit. Here's what I see.
![movie](https://user-images.githubusercontent.com/4316355/78949801-bea10f80-7a9a-11ea-98b0-19f25a7a788f.png)
